version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  flask_app:
    build: .
    depends_on:
      - db
      - redis
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app.main:create_app()

volumes:
  postgres_data:
